// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/FoxLogo.png"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/icon.svg"
    | "/popup.html"
    | "/settings.html"
    | "/youtube.js"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime extends Runtime.Static {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
